services:
  db:
    image: postgres:16
    container_name: postgres_anki
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_anki
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    ports:
      - "4000:4000"
      - "5555:5555"
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend_anki
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_URL: http://backend:4000
    command: npm run start

volumes:
  postgres-data:
